# Generated by Django 4.1.1 on 2022-09-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rollno', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('mailid', models.EmailField(max_length=30)),
            ],
        ),
    ]
