# Generated by Django 4.1.1 on 2022-12-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='rollno',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mailid',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='', max_length=30),
        ),
    ]
