# Generated by Django 4.1.1 on 2022-12-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_rollno_student_age_remove_student_mailid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='image',
            new_name='limage',
        ),
        migrations.AddField(
            model_name='student',
            name='rimage',
            field=models.ImageField(default='', upload_to='media/images'),
        ),
    ]
